/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Clientv1.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.chart.Legend'
    ],

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Spike Detection Application',
                    titleCollapse: false,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            margins: '0 0 0 0',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    title: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            id: 'DateFrom',
                                            margin: '5 0 0 0',
                                            fieldLabel: 'Date From',
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            id: 'TimeFrom',
                                            margin: '5 0 0 10',
                                            fieldLabel: '',
                                            format: 'H:i:s'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            id: 'DateTo',
                                            fieldLabel: 'Date To:',
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'timefield',
                                            id: 'TimeTo',
                                            margin: '0 0 0 10',
                                            fieldLabel: '',
                                            format: 'H:i:s'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            margin: '0 70 0 30',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margins: '5 0 0 0',
                                    id: 'IntervalInput',
                                    fieldLabel: 'Interval',
                                    minValue: 0
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.getCmp('Graph2').surface.removeAll();
                                        Ext.getCmp('Graph2').series.removeAll();

                                        if(Ext.getCmp('RAW1m').getValue()){
                                            Ext.getCmp('Graph2').series.add({
                                                type: 'line',
                                                xField: 'start_date_time',
                                                yField: 'measured_uncorrected',
                                                selectionTolerance: 5,
                                                smooth: 3,
                                                listeners:{
                                                    itemmousedown : function(obj) {
                                                        alert('Its me Bitches');
                                                    }
                                                }
                                            });
                                        }

                                        if(Ext.getCmp('PC1m').getValue()){
                                            Ext.getCmp('Graph2').series.add({
                                                type: 'line',
                                                xField: 'start_date_time',
                                                yField: 'measured_corr_for_pressure',
                                                smooth: 3,
                                                listeners:{
                                                    itemmousedown : function(obj) {
                                                        alert('Its me Bitches');
                                                    }
                                                }
                                            });
                                        }

                                        if(Ext.getCmp('EF1m').getValue()){
                                            Ext.getCmp('Graph2').series.add({
                                                type: 'line',
                                                xField: 'start_date_time',
                                                yField: 'measured_corr_for_efficiency',
                                                smooth: 3,
                                                listeners:{
                                                    itemmousedown : function(obj) {
                                                        alert('Its me Bitches');
                                                    }
                                                }
                                            });
                                        }





                                        //Ext.getCmp('Graph1').surface.removeAll();
                                        //Ext.getCmp('Graph1').series.removeAll();

                                        /*for ($i=1;$i<=18;$i++){
                                        $Zero='';
                                        if ($i<=9) {$Zero='0';}
                                        if(Ext.getCmp('CheckCH'+$Zero+$i).getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch'+$Zero+$i,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch01'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }
                                        }*/


                                        /*if(Ext.getCmp('CheckCH01').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch01',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch01',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch01'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH02').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch02',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch02',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch02'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH03').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch03',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch03',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch03'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH04').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch04',
                                        smooth: 3,
                                        selectionTolerance: 5,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch04',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch04'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH05').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch05',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch05',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch05'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH06').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch06',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch06',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch06'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH07').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch07',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch07',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch07'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH08').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch08',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch08',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch08'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH09').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch09',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch09',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch09'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH10').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch10',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch10',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch10'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH11').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch11',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch11',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch11'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH12').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch12',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch12',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch12'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH13').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch13',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch13',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch13'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH14').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch14',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch14',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch14'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH15').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch15',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch15',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch15'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH16').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch16',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch16',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch16'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH17').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch17',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch17',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch17'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }

                                        if(Ext.getCmp('CheckCH18').getValue()){
                                        Ext.getCmp('Graph1').series.add({
                                        type: 'line',
                                        xField: 'start_date_time',
                                        yField: 'ch18',
                                        selectionTolerance: 5,
                                        smooth: 3,
                                        listeners:{
                                        itemmousedown : function(obj) {
                                        Ext.create('Ext.window.Window',{
                                        title: 'Hi there, Its me ch18',
                                        height: 130,
                                        width: 330,
                                        items: [
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Time:',
                                        value: obj.storeItem.data['start_date_time'],
                                        margin: '0 0 0 30'
                                        },
                                        {
                                        xtype: 'textfield',
                                        fieldLabel: 'Value:',
                                        value: obj.storeItem.data['ch18'],
                                        margin: '0 0 0 30'
                                        }
                                        ]
                                        }).show();
                                        }
                                        }
                                        });
                                        }*/


                                        switch(Ext.getCmp('IntervalInput').getValue()){
                                            case null:
                                            case 0:
                                            case 1:
                                            Ext.getStore('MyJsonPStoreCALMori').getProxy().url="http://localhost/apiv1/CALM/nmdb/CALM_ori/interval/"+Ext.getCmp('DateFrom').getRawValue()+" "+Ext.getCmp('TimeFrom').getRawValue()+"/"+Ext.getCmp('DateTo').getRawValue()+" "+Ext.getCmp('TimeTo').getRawValue();
                                            Ext.getStore('MyJsonPStoreCALMori').load();

                                            Ext.getStore('MyJsonPStorebinTable').getProxy().url="http://localhost/apiv1/CALM/nmdadb/binTable/interval/"+Ext.getCmp('DateFrom').getRawValue()+" "+Ext.getCmp('TimeFrom').getRawValue()+"/"+Ext.getCmp('DateTo').getRawValue()+" "+Ext.getCmp('TimeTo').getRawValue();
                                            Ext.getStore('MyJsonPStorebinTable').load();
                                            break;
                                            default:
                                            Ext.getStore('MyJsonPStoreCALMori').getProxy().url="http://localhost/apiv1/CALM/nmdb/CALM_ori/intervalTuned/"+Ext.getCmp('DateFrom').getRawValue()+" "+Ext.getCmp('TimeFrom').getRawValue()+"/"+Ext.getCmp('DateTo').getRawValue()+" "+Ext.getCmp('TimeTo').getRawValue()+"/"+Ext.getCmp('IntervalInput').getValue();
                                            Ext.getStore('MyJsonPStoreCALMori').load();

                                            Ext.getStore('MyJsonPStorebinTable').getProxy().url="http://localhost/apiv1/CALM/nmdadb/binTable/intervalTuned/"+Ext.getCmp('DateFrom').getRawValue()+" "+Ext.getCmp('TimeFrom').getRawValue()+"/"+Ext.getCmp('DateTo').getRawValue()+" "+Ext.getCmp('TimeTo').getRawValue()+"/"+Ext.getCmp('IntervalInput').getValue();
                                            Ext.getStore('MyJsonPStorebinTable').load();
                                            break;
                                        }


                                        Ext.getCmp('Graph1').redraw();


                                        //Things we do the first time the button is pushed......
                                        if (this.clickCount) {

                                        }else {
                                            Ext.each(Ext.getCmp('Graph1').legend.items, function(item) {

                                                item.fireEvent('mousedown',item);
                                            });
                                            this.clickCount=1;
                                        }


                                    },
                                    id: 'SearchButton',
                                    text: 'Search'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: '',
                    items: [
                        {
                            xtype: 'chart',
                            height: 230,
                            id: 'Graph2',
                            itemId: 'Graph2',
                            width: 400,
                            animate: true,
                            insetPadding: 20,
                            store: 'MyJsonPStoreCALMori',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'start_date_time'
                                    ],
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'measured_uncorrected',
                                        'measured_corr_for_efficiency',
                                        'measured_corr_for_pressure'
                                    ],
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'measured_uncorrected',
                                    smooth: 3
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'checkboxgroup',
                            flex: 1,
                            width: 400,
                            fieldLabel: '1 min original',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    id: 'RAW1m',
                                    boxLabel: 'RAW',
                                    listeners: {
                                        change: {
                                            fn: me.onRAW1mChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    id: 'PC1m',
                                    boxLabel: 'PC',
                                    listeners: {
                                        change: {
                                            fn: me.onPC1mChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    id: 'EF1m',
                                    boxLabel: 'EF',
                                    listeners: {
                                        change: {
                                            fn: me.onEF1mChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            flex: 1,
                            width: 400,
                            fieldLabel: '1 min revised',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'RAW'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'PC'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'EF'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            flex: 1,
                            width: 400,
                            fieldLabel: '1 hour original',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'RAW'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'PC'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'EF'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            flex: 1,
                            width: 400,
                            fieldLabel: '1 hour revised',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'RAW'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'PC'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'EF'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoShow: true,
                    layout: 'fit',
                    title: '',
                    items: [
                        {
                            xtype: 'chart',
                            autoRender: true,
                            height: 280,
                            id: 'Graph1',
                            width: 400,
                            autoSize: true,
                            animate: true,
                            insetPadding: 20,
                            store: 'MyJsonPStorebinTable',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'start_date_time'
                                    ],
                                    majorTickSteps: 6,
                                    minorTickSteps: 4,
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'ch01',
                                        'ch02',
                                        'ch03',
                                        'ch04',
                                        'ch05',
                                        'ch06',
                                        'ch07',
                                        'ch08',
                                        'ch09',
                                        'ch10',
                                        'ch11',
                                        'ch12',
                                        'ch13',
                                        'ch14',
                                        'ch15',
                                        'ch16',
                                        'ch17',
                                        'ch18'
                                    ],
                                    majorTickSteps: 50,
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH01');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch01']);
                                                      }
                                    },
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch01',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH02');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch02']);
                                                      }
                                    },
                                    title: 'CH02',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch02',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH03');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch03']);
                                                      }
                                    },
                                    title: 'CH03',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch03',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH04');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch04']);
                                                      }
                                    },
                                    title: 'CH04',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch04',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH05');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch05']);
                                                      }
                                    },
                                    title: 'CH05',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch05',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH06');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch06']);
                                                      }
                                    },
                                    title: 'CH06',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch06',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH07');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch07']);
                                                      }
                                    },
                                    title: 'CH07',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch07',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH08');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch08']);
                                                      }
                                    },
                                    title: 'CH08',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch08',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH09');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch09']);
                                                      }
                                    },
                                    title: 'CH09',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch09',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH10');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch10']);
                                                      }
                                    },
                                    title: 'CH10',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch10',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH11');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch11']);
                                                      }
                                    },
                                    title: 'CH11',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch11',
                                    markerConfig: {
                                        
                                    },
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH12');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch12']);
                                                      }
                                    },
                                    title: 'CH12',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch12',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH13');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch13']);
                                                      }
                                    },
                                    title: 'CH13',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch13',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH14');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch14']);
                                                      }
                                    },
                                    title: 'CH14',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch14',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH15');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch15']);
                                                      }
                                    },
                                    title: 'CH15',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch15',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH16');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch16']);
                                                      }
                                    },
                                    title: 'CH16',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch16',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH17');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch17']);
                                                      }
                                    },
                                    title: 'CH17',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch17',
                                    selectionTolerance: 2,
                                    smooth: 3
                                },
                                {
                                    type: 'line',
                                    highlight: {
                                        size: 7,
                                        radius: 7
                                    },
                                    tips: {
                                        trackMouse: true,
                                        width: 130,
                                        height: 40,
                                        renderer: function(storeItem, item) {
                                                          this.setTitle('CH18');
                                                          this.update(storeItem.data['start_date_time'].substr(11,8)+"==>"+storeItem.data['ch18']);
                                                      }
                                    },
                                    title: 'CH18',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'ch18',
                                    selectionTolerance: 2,
                                    smooth: 3
                                }
                            ],
                            legend: {

                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRAW1mChange: function(field, newValue, oldValue, eOpts) {
        Ext.getCmp('SearchButton').handler(Ext.getCmp('SearchButton'));
    },

    onPC1mChange: function(field, newValue, oldValue, eOpts) {
        Ext.getCmp('SearchButton').handler(Ext.getCmp('SearchButton'));
    },

    onEF1mChange: function(field, newValue, oldValue, eOpts) {
        Ext.getCmp('SearchButton').handler(Ext.getCmp('SearchButton'));
    }

});