/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Clientv1.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Spike Detection Application',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    title: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            margin: '5 0 0 0',
                                            fieldLabel: 'Date From'
                                        },
                                        {
                                            xtype: 'timefield',
                                            margin: '5 0 0 10',
                                            fieldLabel: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Date To:'
                                        },
                                        {
                                            xtype: 'timefield',
                                            margin: '0 0 0 10',
                                            fieldLabel: ''
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            margin: '0 0 0 30',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margins: '5 0 0 0',
                                    fieldLabel: 'Interval'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        //shits
                                    },
                                    text: 'Search'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: '',
                    items: [
                        {
                            xtype: 'chart',
                            height: 250,
                            width: 400,
                            animate: true,
                            insetPadding: 20,
                            store: 'MyJsonPStoreCALMori',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'start_date_time'
                                    ],
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'measured_uncorrected'
                                    ],
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    axis: 'left',
                                    xField: 'start_date_time',
                                    yField: 'measured_uncorrected',
                                    smooth: 3
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoShow: true,
                    layout: 'fit',
                    title: '',
                    items: [
                        {
                            xtype: 'chart',
                            autoRender: true,
                            height: 250,
                            id: 'Graph1',
                            width: 400,
                            autoSize: true,
                            animate: true,
                            insetPadding: 20,
                            store: 'MyJsonPStorebinTable',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'start_date_time'
                                    ],
                                    majorTickSteps: 50,
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'ch01'
                                    ],
                                    majorTickSteps: 50,
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    xField: 'start_date_time',
                                    yField: 'ch01',
                                    smooth: 3
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});