/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Clientv1.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 250,
    width: 400,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {

                    },
                    itemId: 'mybutton2',
                    text: 'MyButton'
                }
            ]
        });

        me.callParent(arguments);
    }

});