/*
 * File: app/model/binTableModel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Clientv1.model.binTableModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'start_date_time',
            type: 'date'
        },
        {
            name: 'ch01',
            type: 'int'
        },
        {
            name: 'ch02',
            type: 'int'
        },
        {
            name: 'ch03',
            type: 'int'
        },
        {
            name: 'ch04',
            type: 'int'
        },
        {
            name: 'ch05',
            type: 'int'
        },
        {
            name: 'ch06',
            type: 'int'
        },
        {
            name: 'ch07',
            type: 'int'
        },
        {
            name: 'ch08',
            type: 'int'
        },
        {
            name: 'ch09',
            type: 'int'
        },
        {
            name: 'ch10',
            type: 'int'
        },
        {
            name: 'ch11',
            type: 'int'
        },
        {
            name: 'ch12',
            type: 'int'
        },
        {
            name: 'ch13',
            type: 'int'
        },
        {
            name: 'ch14',
            type: 'int'
        },
        {
            name: 'ch15',
            type: 'int'
        },
        {
            name: 'ch16',
            type: 'int'
        },
        {
            name: 'ch17',
            type: 'int'
        },
        {
            name: 'ch18',
            type: 'int'
        },
        {
            name: 'hv1',
            type: 'int'
        },
        {
            name: 'hv2',
            type: 'int'
        },
        {
            name: 'hv3',
            type: 'int'
        },
        {
            name: 'temp_1',
            type: 'int'
        },
        {
            name: 'temp_2',
            type: 'int'
        },
        {
            name: 'atmPressure',
            type: 'int'
        }
    ]
});