/*
 * File: app/model/CALMori.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Clientv1.model.CALMori', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'start_date_time',
            type: 'string'
        },
        {
            name: 'length_time_interval_s',
            type: 'int'
        },
        {
            name: 'measured_uncorrected',
            type: 'float'
        },
        {
            name: 'measured_corr_for_efficiency',
            type: 'float'
        },
        {
            name: 'measured_corr_for_pressure',
            type: 'float'
        },
        {
            name: 'measured_pressure_mbar',
            type: 'float'
        }
    ]
});